### Documentation for classes and data

#' Class \code{"ArtCohort"}
#' 
#' Is a S4 class for the artificial cohort generated by \code{simulateCohort}.
#' 
#' 
#' @name ArtCohort-class
#' @aliases ArtCohort-class [,ArtCohort-method [,ArtCohort,ANY,ANY,ANY-method
#' summary,ArtCohort-method update,ArtCohort-method head,ArtCohort-method
#' tail,ArtCohort-method
#' @slot states.number Object of class \code{"numeric"}: number of states
#' @slot size Object of class \code{"numeric"}: cohort size
#' @slot baseline Object of class \code{"matrix"}: baseline matrix
#' @slot follow.up Object of class \code{"numeric"}: maximum follow-up time
#' @slot parameters Object of class \code{"transition.structure"}: input parameters 
#' @slot parametersCovariances Object of class \code{"transition.structure"}: 
#' input covariance matrices
#' @slot timeToTransition Object of class \code{"matrix"}: 
#' input timeToTransition matrix. logical components
#' @slot transitionFunctions Object of class \code{"transition.structure"}: 
#' input hazard functions
#' @slot time.to.state Object of class \code{"data.frame"}: entry times for each patient into each of the states
#' @docType class
#' @section Objects from the Class: Objects are created by calls to the
#' function \code{simulateCohort}.
#' @author Luisa Salazar Vizcaya, Nello Blaser, Thomas Gsponer
#' @seealso \code{\link{simulateCohort}},
#' \code{\link{transition.structure-class}},
#' \code{\link{transitionProbabilities}}, \code{\link{cumulativeIncidence}}
#' @keywords classes
#' @examples
#' 
#' showClass("ArtCohort")
#' 
NULL

#' Class \code{"PosteriorProbabilities"}
#' 
#' This S4 class summarizes the posterior probabilities over time for objects
#' of class \code{"ArtCohort"}
#' 
#' 
#' @name PosteriorProbabilities-class
#' @aliases PosteriorProbabilities-class [,PosteriorProbabilities-method
#' [,PosteriorProbabilities,ANY,ANY,ANY-method
#' plot,PosteriorProbabilities-method head,PosteriorProbabilities-method
#' tail,PosteriorProbabilities-method
#' @docType class
#' @section Objects from the Class: Objects are created by calls to the
#' function \code{simulateCohort}.
#' @author Luisa Salazar Vizcaya, Nello Blaser, Thomas Gsponer
#' @seealso \code{\link{transitionProbabilities}},
#' \code{\link{cumulativeIncidence}}, \code{\link{ArtCohort-class}}
#' @keywords classes
#' @examples
#' 
#' showClass("PosteriorProbabilities")
#' 
NULL

#' Class \code{"transition.structure"}
#' 
#' This S4 class provides a structure to specify different characteristics of
#' transitions, such as transition functions functions, parameters or parameter
#' covariances.
#' 
#' 
#' @name transition.structure-class
#' @aliases transition.structure-class [[,transition.structure-method
#' [[<-,transition.structure-method print,transition.structure-method
#' @docType class
#' @section Objects from the Class: Objects are created by calls to the
#' functions \code{generateHazardMatrix}, \code{generateParameterMatrix},
#' \code{generateParameterCovarianceMatrix}.
#' @author Luisa Salazar Vizcaya, Nello Blaser, Thomas Gsponer
#' @seealso \code{\link{generateHazardMatrix}},
#' \code{\link{generateParameterMatrix}},
#' \code{\link{generateParameterCovarianceMatrix}}
#' @keywords classes
#' @examples
#' 
#'   showClass("transition.structure")
#' 
NULL

#' tavi data set
#' 
#' The simulated data set for each patient contains data for kidney injuries,
#' bleeding complications and the combined endpoint of stroke or death. The
#' data was simulated from the original data following the steps described in
#' the package vignette.
#' 
#' 
#' @name tavi
#' @docType data
#' @format A data frame with 194 observations on the following 7 variables.
#' \describe{
#' \item{id}{a character vector that contains the patient
#' id's} 
#' \item{kidney}{a numeric vector; indicator variable that show
#' if an event has occurred} 
#' \item{kidney.dur}{a numeric vector; times
#' at which the events occurred or the patients were censored}
#' \item{bleeding}{a numeric vector; indicator variable that show if an
#' event has occurred} 
#' \item{bleeding.dur}{a numeric vector; times at
#' which the events occurred or the patients were censored}
#' \item{death}{a numeric vector; indicator variable that show if an
#' event has occurred} 
#' \item{death.dur}{a numeric vector; times at
#' which the events occurred or the patients were censored} 
#' }
#' @keywords datasets
#' @examples
#' 
#' head(data(tavi))
#' 
NULL