### Documentation for classes and data

#' Class \code{"ArtCohort"}
#' 
#' Is a S4 class for the artificial cohort generated by \code{simulateCohort}.
#' 
#' 
#' @name ArtCohort-class
#' @aliases ArtCohort-class [,ArtCohort-method [,ArtCohort,ANY,ANY,ANY-method
#' summary,ArtCohort-method update,ArtCohort-method head,ArtCohort-method
#' tail,ArtCohort-method
#' @docType class
#' @section Objects from the Class: Objects are created by calls to the
#' function \code{simulateCohort}.
#' @author Luisa Salazar Vizcaya, Nello Blaser, Thomas Gsponer
#' @seealso \code{\link{simulateCohort}},
#' \code{\link{transition.structure-class}},
#' \code{\link{transitionProbabilities}}, \code{\link{cumulativeIncidence}}
#' @keywords classes
#' @examples
#' 
#' showClass("ArtCohort")
#' 
NULL

#' Class \code{"PosteriorProbabilities"}
#' 
#' This S4 class summarizes the posterior probabilities over time for objects
#' of class \code{"ArtCohort"}
#' 
#' 
#' @name PosteriorProbabilities-class
#' @aliases PosteriorProbabilities-class [,PosteriorProbabilities-method
#' [,PosteriorProbabilities,ANY,ANY,ANY-method
#' plot,PosteriorProbabilities-method head,PosteriorProbabilities-method
#' tail,PosteriorProbabilities-method
#' @docType class
#' @section Objects from the Class: Objects are created by calls to the
#' function \code{simulateCohort}.
#' @author Luisa Salazar Vizcaya, Nello Blaser, Thomas Gsponer
#' @seealso \code{\link{transitionProbabilities}},
#' \code{\link{cumulativeIncidence}}, \code{\link{ArtCohort-class}}
#' @keywords classes
#' @examples
#' 
#' showClass("PosteriorProbabilities")
#' 
NULL

#' Class \code{"transition.structure"}
#' 
#' This S4 class provides a structure to specify different characteristics of
#' transitions, such as transition functions functions, parameters or parameter
#' covariances.
#' 
#' 
#' @name transition.structure-class
#' @aliases transition.structure-class [[,transition.structure-method
#' [[<-,transition.structure-method print,transition.structure-method
#' @docType class
#' @section Objects from the Class: Objects are created by calls to the
#' functions \code{generateHazardMatrix}, \code{generateParameterMatrix},
#' \code{generateParameterCovarianceMatrix}.
#' @author Luisa Salazar Vizcaya, Nello Blaser, Thomas Gsponer
#' @seealso \code{\link{generateHazardMatrix}},
#' \code{\link{generateParameterMatrix}},
#' \code{\link{generateParameterCovarianceMatrix}}
#' @keywords classes
#' @examples
#' 
#'   showClass("transition.structure")
#' 
NULL

#' tavi data set
#' 
#' The simulated data set for each patient contains data for kidney injuries,
#' bleeding complications and the combined endpoint of stroke or death. The
#' data was simulated from the original data following the steps described in
#' the package vignette.
#' 
#' 
#' @name tavi
#' @docType data
#' @format A data frame with 194 observations on the following 7 variables.
#' \describe{ \item{list("id")}{a character vector that contains the patient
#' id's} \item{list("kidney")}{a numeric vector; indicator variable that show
#' if an event has occurred} \item{list("kidney.dur")}{a numeric vector; times
#' at which the events occurred or the patients were censored}
#' \item{list("bleeding")}{a numeric vector; indicator variable that show if an
#' event has occurred} \item{list("bleeding.dur")}{a numeric vector; times at
#' which the events occurred or the patients were censored}
#' \item{list("death")}{a numeric vector; indicator variable that show if an
#' event has occurred} \item{list("death.dur")}{a numeric vector; times at
#' which the events occurred or the patients were censored} }
#' @keywords datasets
#' @examples
#' 
#' head(data(tavi))
#' 
NULL